import { Router, type IRouter } from "express";
import healthRouter from "./health";
import departmentsRouter from "./departments";
import studentsRouter from "./students";
import staffRouter from "./staff";
import coursesRouter from "./courses";
import subjectsRouter from "./subjects";
import attendanceRouter from "./attendance";
import feesRouter from "./fees";
import examsRouter from "./exams";
import dashboardRouter from "./dashboard";
import razorpayRouter from "./razorpay";
import hostelsRouter from "./hostels";
import transportRouter from "./transport";
import libraryRouter from "./library";
import eventsRouter from "./events";
import communicationsRouter from "./communications";
import inventoryRouter from "./inventory";
import timetableRouter from "./timetable";
import assignmentsRouter from "./assignments";
import certificatesRouter from "./certificates";
import leavesRouter from "./leaves";
import disciplinaryRouter from "./disciplinary";
import feeInstalmentsRouter from "./feeInstalments";
import scholarshipsRouter from "./scholarships";
import condonationRouter from "./condonation";
import settingsRouter from "./settings";
import reportsRouter from "./reports";
import payrollRouter from "./payroll";
import academicCalendarRouter from "./academicCalendar";
import cgpaRouter from "./cgpa";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(departmentsRouter);
router.use(studentsRouter);
router.use(staffRouter);
router.use(coursesRouter);
router.use(subjectsRouter);
router.use(attendanceRouter);
router.use(feesRouter);
router.use(examsRouter);
router.use(razorpayRouter);
router.use(hostelsRouter);
router.use(transportRouter);
router.use(libraryRouter);
router.use(eventsRouter);
router.use(communicationsRouter);
router.use(inventoryRouter);
router.use(timetableRouter);
router.use(assignmentsRouter);
router.use(certificatesRouter);
router.use(leavesRouter);
router.use(disciplinaryRouter);
router.use(feeInstalmentsRouter);
router.use(scholarshipsRouter);
router.use(condonationRouter);
router.use(settingsRouter);
router.use(reportsRouter);
router.use(payrollRouter);
router.use(academicCalendarRouter);
router.use(cgpaRouter);

export default router;
