import { Router, type IRouter } from "express";
import healthRouter from "./health";
import departmentsRouter from "./departments";
import studentsRouter from "./students";
import staffRouter from "./staff";
import coursesRouter from "./courses";
import subjectsRouter from "./subjects";
import attendanceRouter from "./attendance";
import feesRouter from "./fees";
import examsRouter from "./exams";
import dashboardRouter from "./dashboard";
import razorpayRouter from "./razorpay";
import hostelsRouter from "./hostels";
import transportRouter from "./transport";
import libraryRouter from "./library";
import eventsRouter from "./events";
import communicationsRouter from "./communications";
import inventoryRouter from "./inventory";
import timetableRouter from "./timetable";
import assignmentsRouter from "./assignments";
import certificatesRouter from "./certificates";
import leavesRouter from "./leaves";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(departmentsRouter);
router.use(studentsRouter);
router.use(staffRouter);
router.use(coursesRouter);
router.use(subjectsRouter);
router.use(attendanceRouter);
router.use(feesRouter);
router.use(examsRouter);
router.use(razorpayRouter);
router.use(hostelsRouter);
router.use(transportRouter);
router.use(libraryRouter);
router.use(eventsRouter);
router.use(communicationsRouter);
router.use(inventoryRouter);
router.use(timetableRouter);
router.use(assignmentsRouter);
router.use(certificatesRouter);
router.use(leavesRouter);

export default router;
